
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import styles from '../login/styles/login.module.css'
const inter = Inter({ subsets: ['latin'] })
export default function Login() {
  return (
    <section className={styles.sectionContainer}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.mainContainer}>
        <Image
          src="login.svg"
          alt="Login"
          width={800}
          height={800}
        />
        <form>
          <div className={styles.inputContainer}>
            <h1 className={styles.logintitle}>Bem-vindo ao Login 🙌</h1>
            <div className={styles.line} />
            <input className={styles.input} type="text" placeholder="E-mail" />
            <input className={styles.input} type="password" placeholder="Senha" />
            <div className={styles.rememberAndPasswordContainer}>
              <div className={styles.rememberContainer}>
                <input type="checkbox" />
                <label>Lembrar-me</label>
              </div>
              <Link className={styles.passwordContainer} href="#">Esqueceu a senha?</Link>
            </div>
            <button className={styles.button} type="submit">Entrar</button>
          </div>
          <div className={styles.registerContainer}>
            <Link href="#">Não tem uma conta? <span className={styles.registerSpan}>Cadastre-se</span></Link>
          </div>
        </form>
      </main>
    </section>
  )
} 