export type TMapCategories =
  | 'todos'
  | 'evento'
  | 'sala'
  | 'laboratório'
  | 'secretaria'
  | 'biblioteca'
  | 'auditório'
  | 'banheiro'
  | 'lanchonete'
  | 'clínica'
  | 'lazer'
  | 'acessibilidade'
  | 'estacionamento'
  | 'outros'
